import asyncio
import os
import sys

# Ensure backend root is in sys.path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.core.database import AsyncSessionLocal, engine, Base
from app.models.db_models import Camera, Watchlist, Detection
from sqlalchemy.future import select

OFFICIAL_CAMERAS_DATA = [
    {
        "camera_code": "cam01",
        "name": "01 Chimanbhai Bridge",
        "department": "Gujarat Traffic Police",
        "camera_type": "ANPR HSRP",
        "ownership": "Ahmedabad Traffic Police",
        "location_name": "Chimanbhai Patel Overbridge, Sabarmati, Ahmedabad",
        "latitude": 23.0645,
        "longitude": 72.5831,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam01",
        "hls_url": "https://cctv.corp8.cloud/cam01/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam01/whep",
        "coverage_radius_meters": 200.0,
        "installation_year": 2023,
        "storage_details": "NVR 30-Day On-Premise",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam02",
        "name": "02 Janpath",
        "department": "Ahmedabad Municipal Corporation",
        "camera_type": "PTZ Dome",
        "ownership": "AMC Smart City Command Center",
        "location_name": "Janpath Hotel Cross Road, Ashram Road, Ahmedabad",
        "latitude": 23.0338,
        "longitude": 72.5562,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam02",
        "hls_url": "https://cctv.corp8.cloud/cam02/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam02/whep",
        "coverage_radius_meters": 180.0,
        "installation_year": 2024,
        "storage_details": "SDC SAN Storage 60 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam03",
        "name": "03 O.N.G.C. Office",
        "department": "State Security Branch (SSB)",
        "camera_type": "Fixed Bullet",
        "ownership": "ONGC Security & Gujarat Police",
        "location_name": "ONGC Office Gate 1, Chandkheda, Ahmedabad",
        "latitude": 23.0815,
        "longitude": 72.5892,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam03",
        "hls_url": "https://cctv.corp8.cloud/cam03/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam03/whep",
        "coverage_radius_meters": 150.0,
        "installation_year": 2022,
        "storage_details": "Local NVR 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam04",
        "name": "04 Paldi Circle",
        "department": "Gujarat Traffic Police",
        "camera_type": "ANPR HSRP",
        "ownership": "Ahmedabad City Police",
        "location_name": "Paldi Cross Road & Bus Station, Ahmedabad",
        "latitude": 23.0135,
        "longitude": 72.5623,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam04",
        "hls_url": "https://cctv.corp8.cloud/cam04/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam04/whep",
        "coverage_radius_meters": 220.0,
        "installation_year": 2024,
        "storage_details": "Smart City Cloud 45 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam05",
        "name": "05 Visat Teen Rasta",
        "department": "Gujarat Traffic Police",
        "camera_type": "Fixed Bullet",
        "ownership": "Sabarmati Traffic Division",
        "location_name": "Visat Petrol Pump Tri-Junction, Sabarmati, Ahmedabad",
        "latitude": 23.1022,
        "longitude": 72.5830,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam05",
        "hls_url": "https://cctv.corp8.cloud/cam05/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam05/whep",
        "coverage_radius_meters": 160.0,
        "installation_year": 2023,
        "storage_details": "Edge SD 128GB + NVR",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam06",
        "name": "06 Timbavadi Gate - Junagadh",
        "department": "Junagadh Police",
        "camera_type": "PTZ Dome",
        "ownership": "Junagadh Smart City",
        "location_name": "Timbavadi Entry Gate, Junagadh City",
        "latitude": 21.5034,
        "longitude": 70.4578,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam06",
        "hls_url": "https://cctv.corp8.cloud/cam06/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam06/whep",
        "coverage_radius_meters": 190.0,
        "installation_year": 2021,
        "storage_details": "City NVR 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam07",
        "name": "07 Hero Showroom - Gir Somnath",
        "department": "Gir Somnath Police",
        "camera_type": "Fixed Bullet",
        "ownership": "Veraval Police Station",
        "location_name": "National Highway Junction near Hero Showroom, Veraval",
        "latitude": 20.9042,
        "longitude": 70.3688,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam07",
        "hls_url": "https://cctv.corp8.cloud/cam07/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam07/whep",
        "coverage_radius_meters": 150.0,
        "installation_year": 2022,
        "storage_details": "NVR 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam08",
        "name": "08 Majewadi Gate - Junagadh",
        "department": "Junagadh Police",
        "camera_type": "ANPR HSRP",
        "ownership": "Junagadh City Police",
        "location_name": "Historical Majewadi Darwaza, Junagadh",
        "latitude": 21.5245,
        "longitude": 70.4632,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam08",
        "hls_url": "https://cctv.corp8.cloud/cam08/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam08/whep",
        "coverage_radius_meters": 175.0,
        "installation_year": 2023,
        "storage_details": "SDC SAN 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam09",
        "name": "09 New Bypass Circle - Junagadh",
        "department": "Gujarat Highway Patrol",
        "camera_type": "PTZ Dome",
        "ownership": "Roads & Buildings Department",
        "location_name": "National Highway 8D Bypass Circle, Junagadh",
        "latitude": 21.5380,
        "longitude": 70.4490,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam09",
        "hls_url": "https://cctv.corp8.cloud/cam09/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam09/whep",
        "coverage_radius_meters": 250.0,
        "installation_year": 2024,
        "storage_details": "Toll Plaza Server 45 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam10",
        "name": "10 Char Chowk Road - Junagadh",
        "department": "Junagadh Police",
        "camera_type": "Fixed Bullet",
        "ownership": "Junagadh Municipality",
        "location_name": "Central Commercial Char Chowk, Junagadh",
        "latitude": 21.5190,
        "longitude": 70.4600,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam10",
        "hls_url": "https://cctv.corp8.cloud/cam10/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam10/whep",
        "coverage_radius_meters": 140.0,
        "installation_year": 2021,
        "storage_details": "Local NVR 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam11",
        "name": "11 Dolatpara - Junagadh",
        "department": "Gujarat Industrial Development (GIDC)",
        "camera_type": "Fixed Bullet",
        "ownership": "GIDC Security & Police",
        "location_name": "Dolatpara Industrial Estate Gate, Junagadh",
        "latitude": 21.5450,
        "longitude": 70.4720,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam11",
        "hls_url": "https://cctv.corp8.cloud/cam11/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam11/whep",
        "coverage_radius_meters": 160.0,
        "installation_year": 2022,
        "storage_details": "Local NVR 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam12",
        "name": "12 Tri Mandir Adalaj Tollnaka",
        "department": "Gandhinagar Police",
        "camera_type": "ANPR HSRP",
        "ownership": "Gujarat Highway Police",
        "location_name": "Adalaj Toll Plaza, Gandhinagar Highway",
        "latitude": 23.1812,
        "longitude": 72.5845,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam12",
        "hls_url": "https://cctv.corp8.cloud/cam12/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam12/whep",
        "coverage_radius_meters": 260.0,
        "installation_year": 2024,
        "storage_details": "SDC Central 60 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam13",
        "name": "13 CN Vidhyalaya",
        "department": "Ahmedabad Municipal Corporation",
        "camera_type": "Dome Camera",
        "ownership": "Ellisbridge Police Station",
        "location_name": "CN Vidhyalaya Campus Cross Road, Ambawadi, Ahmedabad",
        "latitude": 23.0234,
        "longitude": 72.5456,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam13",
        "hls_url": "https://cctv.corp8.cloud/cam13/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam13/whep",
        "coverage_radius_meters": 130.0,
        "installation_year": 2023,
        "storage_details": "School Node NVR 15 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam14",
        "name": "14 Delight RLVD",
        "department": "Gujarat Traffic Police",
        "camera_type": "ANPR HSRP",
        "ownership": "Traffic Control Room Ahmedabad",
        "location_name": "Red Light Violation Detection Node - SG Road, Ahmedabad",
        "latitude": 23.0310,
        "longitude": 72.5180,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam14",
        "hls_url": "https://cctv.corp8.cloud/cam14/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam14/whep",
        "coverage_radius_meters": 180.0,
        "installation_year": 2024,
        "storage_details": "RLVD e-Challan Server 90 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam15",
        "name": "15 Suvidha Park",
        "department": "Ahmedabad City Police",
        "camera_type": "Fixed Bullet",
        "ownership": "Vastrapur Police Station",
        "location_name": "Suvidha Shopping & Residential Park, Ahmedabad",
        "latitude": 23.0450,
        "longitude": 72.5320,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam15",
        "hls_url": "https://cctv.corp8.cloud/cam15/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam15/whep",
        "coverage_radius_meters": 140.0,
        "installation_year": 2022,
        "storage_details": "Local NVR 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam16",
        "name": "16 Visat P2",
        "department": "Gujarat Police",
        "camera_type": "PTZ Dome",
        "ownership": "Ahmedabad Smart City",
        "location_name": "Visat BRTS Terminal Corridor P2, Ahmedabad",
        "latitude": 23.1050,
        "longitude": 72.5850,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam16",
        "hls_url": "https://cctv.corp8.cloud/cam16/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam16/whep",
        "coverage_radius_meters": 200.0,
        "installation_year": 2023,
        "storage_details": "BRTS Surveillance Server 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam17",
        "name": "17 Rajkot Bus Port CCTV",
        "department": "GSRTC (State Transport)",
        "camera_type": "ANPR HSRP",
        "ownership": "GSRTC & Rajkot Police",
        "location_name": "Rajkot Central Bus Port Terminal Ingate",
        "latitude": 22.3039,
        "longitude": 70.8022,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam17",
        "hls_url": "https://cctv.corp8.cloud/cam17/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam17/whep",
        "coverage_radius_meters": 180.0,
        "installation_year": 2024,
        "storage_details": "GSRTC Hub Storage 45 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam18",
        "name": "18 Rajkot CCTV Junction",
        "department": "Rajkot Municipal Corporation",
        "camera_type": "Fixed Bullet",
        "ownership": "RMC Netram Command Center",
        "location_name": "Kasturba Road & Trikon Baug, Rajkot",
        "latitude": 22.2980,
        "longitude": 70.7950,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam18",
        "hls_url": "https://cctv.corp8.cloud/cam18/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam18/whep",
        "coverage_radius_meters": 150.0,
        "installation_year": 2022,
        "storage_details": "RMC Netram SDC 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam19",
        "name": "19 Khaparia Gram Panchayat - Navsari",
        "department": "Panchayat & Rural Development",
        "camera_type": "Fixed Bullet",
        "ownership": "Gandevi Taluka Police",
        "location_name": "Khaparia Gram Panchayat Bhawan, Navsari District",
        "latitude": 20.8120,
        "longitude": 72.9840,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam19",
        "hls_url": "https://cctv.corp8.cloud/cam19/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam19/whep",
        "coverage_radius_meters": 120.0,
        "installation_year": 2023,
        "storage_details": "Panchayat Solar Edge SD 64GB",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam20",
        "name": "20 Mohanpura",
        "department": "Gujarat Police",
        "camera_type": "Fixed Bullet",
        "ownership": "North Gujarat Range Police",
        "location_name": "Mohanpura State Highway Junction",
        "latitude": 23.8500,
        "longitude": 72.1250,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam20",
        "hls_url": "https://cctv.corp8.cloud/cam20/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam20/whep",
        "coverage_radius_meters": 140.0,
        "installation_year": 2022,
        "storage_details": "Local NVR 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam21",
        "name": "23 Patan Dethali Char Rasta",
        "department": "Patan Police",
        "camera_type": "PTZ Dome",
        "ownership": "Patan Municipality",
        "location_name": "Dethali Char Rasta Ring Road, Patan",
        "latitude": 23.8340,
        "longitude": 72.1380,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam21",
        "hls_url": "https://cctv.corp8.cloud/cam21/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam21/whep",
        "coverage_radius_meters": 200.0,
        "installation_year": 2024,
        "storage_details": "Patan Netram Server 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam22",
        "name": "28 BK Mervada Tran Rasta",
        "department": "Banaskantha Police",
        "camera_type": "Fixed Bullet",
        "ownership": "Banaskantha Border Police",
        "location_name": "Mervada Tran Rasta Checkpost, Banaskantha",
        "latitude": 24.1720,
        "longitude": 72.4340,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam22",
        "hls_url": "https://cctv.corp8.cloud/cam22/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam22/whep",
        "coverage_radius_meters": 170.0,
        "installation_year": 2023,
        "storage_details": "Checkpost NVR 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam23",
        "name": "30 Kheram",
        "department": "Gujarat Highway Patrol",
        "camera_type": "Fixed Bullet",
        "ownership": "Surendranagar Police",
        "location_name": "Kheram Toll Link, Surendranagar Highway",
        "latitude": 22.7500,
        "longitude": 71.5000,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam23",
        "hls_url": "https://cctv.corp8.cloud/cam23/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam23/whep",
        "coverage_radius_meters": 150.0,
        "installation_year": 2022,
        "storage_details": "Highway NVR 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam24",
        "name": "33 Dehgam",
        "department": "Gandhinagar Police",
        "camera_type": "ANPR HSRP",
        "ownership": "Dehgam Municipality",
        "location_name": "Dehgam ST Bus Station Circle, Gandhinagar",
        "latitude": 23.1670,
        "longitude": 72.8120,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam24",
        "hls_url": "https://cctv.corp8.cloud/cam24/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam24/whep",
        "coverage_radius_meters": 190.0,
        "installation_year": 2024,
        "storage_details": "Gandhinagar SDC 45 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam25",
        "name": "34 Dhanori",
        "department": "Navsari Police",
        "camera_type": "Fixed Bullet",
        "ownership": "Navsari Rural Police",
        "location_name": "Dhanori Cross Road, Navsari District",
        "latitude": 20.8900,
        "longitude": 73.0100,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam25",
        "hls_url": "https://cctv.corp8.cloud/cam25/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam25/whep",
        "coverage_radius_meters": 140.0,
        "installation_year": 2023,
        "storage_details": "Local NVR 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam26",
        "name": "35 Tankal",
        "department": "Navsari Police",
        "camera_type": "Fixed Bullet",
        "ownership": "Navsari Rural Police",
        "location_name": "Tankal Village Gate Junction, Navsari",
        "latitude": 20.7600,
        "longitude": 73.0800,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam26",
        "hls_url": "https://cctv.corp8.cloud/cam26/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam26/whep",
        "coverage_radius_meters": 130.0,
        "installation_year": 2021,
        "storage_details": "Edge SD 128GB",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam27",
        "name": "36 Bilimora Railway Crossing",
        "department": "Western Railway & Gujarat Police",
        "camera_type": "PTZ Dome",
        "ownership": "Bilimora RPF & Town Police",
        "location_name": "Level Crossing Gate 112, Bilimora, Navsari",
        "latitude": 20.7620,
        "longitude": 72.9650,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam27",
        "hls_url": "https://cctv.corp8.cloud/cam27/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam27/whep",
        "coverage_radius_meters": 200.0,
        "installation_year": 2023,
        "storage_details": "Station Server 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam28",
        "name": "37 Bilimora Town Gate",
        "department": "Bilimora Municipality",
        "camera_type": "ANPR HSRP",
        "ownership": "Bilimora Nagar Palika",
        "location_name": "Deshra Road & Town Welcome Arch, Bilimora",
        "latitude": 20.7640,
        "longitude": 72.9690,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam28",
        "hls_url": "https://cctv.corp8.cloud/cam28/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam28/whep",
        "coverage_radius_meters": 180.0,
        "installation_year": 2024,
        "storage_details": "Nagar Palika Control Room 45 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam29",
        "name": "38 Bilimora Highway Junction",
        "department": "Gujarat Highway Patrol",
        "camera_type": "PTZ Dome",
        "ownership": "Highway Traffic Police Navsari",
        "location_name": "State Highway 6 Connector, Bilimora Bypass",
        "latitude": 20.7680,
        "longitude": 72.9750,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam29",
        "hls_url": "https://cctv.corp8.cloud/cam29/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam29/whep",
        "coverage_radius_meters": 220.0,
        "installation_year": 2022,
        "storage_details": "Highway NVR 30 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    },
    {
        "camera_code": "cam30",
        "name": "30 Gandhidham Rambaugh P2",
        "department": "Kutch East Police",
        "camera_type": "ANPR HSRP",
        "ownership": "Deendayal Port Trust & Gandhidham Police",
        "location_name": "Rambaugh Hospital Cross Road P2, Gandhidham, Kutch",
        "latitude": 23.0760,
        "longitude": 70.1340,
        "rtsp_url": "rtsp://103.250.160.189:8554/stream/cam30",
        "hls_url": "https://cctv.corp8.cloud/cam30/index.m3u8",
        "webrtc_url": "http://103.250.160.189:8889/stream/cam30/whep",
        "coverage_radius_meters": 240.0,
        "installation_year": 2024,
        "storage_details": "Port Security SDC 60 Days",
        "maintenance_status": "Operational",
        "fps_processing": 15
    }
]

async def seed():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
        
    async with AsyncSessionLocal() as session:
        # Clear existing mock cameras
        existing_res = await session.execute(select(Camera))
        existing_cams = existing_res.scalars().all()
        for cam in existing_cams:
            await session.delete(cam)
        await session.commit()
        
        print("Cleared previous demo cameras.")
        
        # Insert all 30 real Gujarat Police sandbox cameras
        for cdata in OFFICIAL_CAMERAS_DATA:
            cam = Camera(**cdata)
            session.add(cam)
            
        await session.commit()
        print(f"Successfully seeded {len(OFFICIAL_CAMERAS_DATA)} official Gujarat Police cameras into database!")

if __name__ == "__main__":
    asyncio.run(seed())
